In [2]:
import numpy as np

1-D Array

In [3]:
list=[8,9,7,6]
type(list)

list

In [8]:
nump=np.array(list)
type(nump)

numpy.ndarray

3-D Array

In [17]:
three_D=[[[1,2,3],[2,3,4]],[[4,5,6],[7,8,9]]]
b=np.array(three_D)
b

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [19]:
b.ndim

3

In [20]:
b.shape

(2, 2, 3)

In [21]:
z=np.zeros((2,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
l=np.linspace(0,30,5)
l

array([ 0. ,  7.5, 15. , 22.5, 30. ])

2-D Array

In [10]:
two_D=[[1,2,3],[2,3,4],[3,4,5]]
a=np.array(two_D)
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
a.ndim

2

a.shape

Random numbers

In [27]:
np.random.rand(5,3)

array([[5.47182363e-01, 3.97995832e-01, 9.60011154e-01],
       [4.69059028e-01, 3.36640105e-01, 6.12321554e-01],
       [3.28319841e-01, 3.13831473e-01, 9.40566712e-01],
       [9.16950368e-01, 7.90147003e-04, 9.90262779e-01],
       [9.01473443e-01, 8.25650578e-01, 4.51882863e-01]])

In [29]:
r=np.random.randint(1,18,(3,4))
r

array([[ 1, 17, 12,  7],
       [ 1,  2,  3, 12],
       [ 5,  3,  6,  7]])

In [30]:
np.random.randn(6,3)

array([[ 0.48072562, -0.08871622,  0.24635689],
       [ 0.71914892, -1.0686306 ,  0.92626384],
       [ 1.67082091,  0.03773898, -2.24539387],
       [ 0.17691674,  0.44658875,  1.80408526],
       [-0.28067837, -0.85054404,  0.45928285],
       [-0.40073892,  0.3681064 , -0.15896047]])

In [31]:
r[0:3,0:3]

array([[ 1, 17, 12],
       [ 1,  2,  3],
       [ 5,  3,  6]])

In [34]:
r.reshape(3,4)

array([[ 1, 17, 12,  7],
       [ 1,  2,  3, 12],
       [ 5,  3,  6,  7]])

In [38]:
r[2]

array([5, 3, 6, 7])

In [40]:
np.sum(r[2])

21

In [41]:
np.min(r[2])

3

In [44]:
r[2].argmax()#shows the maximum value's index.

3

In [46]:
r[2].argmin()#shows the minimum value's index

1

In [47]:
a=np.random.randint(1,10000,(100,2))
a

array([[2866, 9355],
       [2291, 1514],
       [1883, 4560],
       [ 399, 7513],
       [9469, 3893],
       [5556, 7385],
       [7797, 9977],
       [2256, 4393],
       [5843,  811],
       [ 258, 2439],
       [2506, 8106],
       [5076,  651],
       [1648, 2865],
       [8914, 6625],
       [6311, 4550],
       [1906, 2264],
       [5461, 5933],
       [ 827, 1006],
       [6893, 4477],
       [1799, 3779],
       [8117,  952],
       [6691, 8738],
       [ 799,  567],
       [2651, 4005],
       [9628, 5841],
       [6839, 3351],
       [8208, 2130],
       [5274, 5041],
       [4522, 3382],
       [5043, 8982],
       [5911, 9999],
       [8626,  486],
       [9909, 9669],
       [ 479, 4020],
       [8337, 1997],
       [1446, 4556],
       [3663, 8496],
       [9714, 1613],
       [9332, 6421],
       [1192, 2270],
       [4646, 9689],
       [ 331, 7741],
       [9206, 6908],
       [ 605, 5739],
       [9723, 9461],
       [3322, 4636],
       [8214, 5636],
       [ 726,

In [52]:
z=range(1000)
z

%timeit [i//2 for i in z]

106 µs ± 4.49 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [53]:
p=np.arange(1000)
%timeit p//2

3.59 µs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
